const paragraphs = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer dignissim mi eget sem dapibus feugiat. Suspendisse sagittis dignissim erat at cursus. Duis viverra erat in tortor condimentum pulvinar. Nullam mollis eget massa vel rutrum. Vivamus mattis vitae odio vel aliquam. Phasellus id risus eget ligula vehicula faucibus. Donec orci sem, volutpat at lorem volutpat, accumsan posuere lorem. In hac habitasse platea dictumst. Praesent venenatis est in bibendum ornare.",
  "Vivamus elementum accumsan cursus. In ac purus tempus, viverra urna ac, dignissim risus. Duis mattis leo at enim congue, eget aliquet augue vulputate. Suspendisse maximus lacus sagittis dolor mattis, pharetra imperdiet sapien sollicitudin. Morbi vulputate viverra mi. Aenean id aliquet ligula, sed porta enim. Integer tristique arcu erat, at scelerisque dui malesuada ac. Maecenas vitae accumsan massa. Phasellus vitae mi eros. Ut rhoncus libero sed fringilla malesuada. Mauris eleifend feugiat quam sed aliquam. Pellentesque feugiat non quam sed lacinia. Integer pulvinar in lectus eu fringilla.",
  "Sed vel facilisis urna. Nullam velit quam, posuere ac commodo et, vestibulum in nunc. Suspendisse iaculis nibh elementum ante commodo vestibulum. Cras a mi eros. Proin blandit lacinia libero nec dapibus. Morbi finibus dictum nisl, sed dignissim urna consequat ut. Proin vel eros arcu. Vivamus molestie pellentesque lacinia. Suspendisse potenti. Nunc sit amet sapien at elit iaculis porttitor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ac vestibulum neque.",
  "Vestibulum tempor fringilla eros, eu eleifend augue accumsan nec. Fusce odio ante, pretium viverra nisi vel, iaculis cursus magna. Ut velit odio, ultrices rutrum semper vitae, maximus quis ipsum. Nullam a justo sit amet ipsum tempus porta vitae et leo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur eu porta mauris. Cras at felis vitae ante interdum faucibus. Morbi hendrerit, erat non fringilla suscipit, diam nisl tincidunt urna, eu fringilla justo orci at justo. Fusce in mattis massa. Cras imperdiet cursus metus, iaculis sodales dui commodo eu. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam non molestie sapien. Mauris vestibulum nunc id erat dictum, id mattis est auctor. In imperdiet interdum dignissim. Vivamus viverra mauris et tincidunt lacinia.",
  "Pellentesque eu elit non lorem congue fermentum. Ut augue velit, sollicitudin sed viverra a, vehicula sed dolor. Duis finibus, leo imperdiet accumsan ultrices, est risus sollicitudin mauris, ut tincidunt diam est nec nunc. In ac ipsum ligula. Nam eget dui commodo, porttitor nibh ut, pulvinar sapien. Donec finibus, nisl quis lobortis facilisis, nisi mi consequat urna, vel aliquet nisi tortor eget sem. Cras sed accumsan odio. Etiam non sapien facilisis, fringilla metus et, tincidunt lacus. In at lobortis nisl. Sed et dapibus turpis, non vestibulum risus.",
];

export default paragraphs;
